### PR TITLE
Update Slovak locale

### PR DESCRIPTION
**Pull request by RobiNN1**

### CODE REVIEW

**Comment by RobiNN1** [comment]
Can you merge this? So we can use it

**Comment by katomaro** [comment]
@RobiNN1 from a developer's perspective, you should have sent typo fixes for English text (like seen on [very first Line](https://github.com/Zrips/CMILib/blob/0dfd48c0a741a3385e07d7608961d0a198d33c5c/Translations/Locale_SK.yml#L1)) on a separate PR for the (I guess main) Locale_EN.yml file, as it is likely that the other locales just inherit changes (like line additions) from it, sending such changes to a specific locale file would require to sync them back to the main one which is troublesome. EN might not be the main locale that the Developer uses, but it still is the main language that is used.

On another note, it's not really etiquette to close a PR just because it had no reply in a month, there's a lot happening in the world right now, our life is but a single drop in the ocean in the grand scheme of things (and deleting repo doesn't really stop people from viewing changes). I understand if you weren't aware that removing the repository from your account (deleting fork, again, run git blame on that link, git attributes changes to your email and github just tracks that) would close the PR before review, but still, you could have opened another one with the translations.

Anyhow, I believe it would have been denied because on top of the translations you also customized the outputs, and customization =/= translation.
I say this from a quick overview, for example, on [Line 58](https://github.com/Zrips/CMILib/blob/0dfd48c0a741a3385e07d7608961d0a198d33c5c/Translations/Locale_SK.yml#L58) you wiped the red "[SERVER]" from the message (+ it was already translated, so no reason to edit it), while said customization may be applicable to your server, it is definitely something that is your liking and not the developer's vision (and he just asks for translations).

Aaaaand if it were to be denied, you could still use the plugin changes locally by placing the file under `~/plugins/CMILib/Translations`, in fact, this is what you should do in order to customize the messages for your server.

**Comment by RobiNN1** [comment]
These were not new changes. I translated it from scratch because the original was soo bad. There are no customizations.

And I deleted the repo, which automatically closed the PR..

**Comment by katomaro** [comment]
> There are 0 customizations, just compare it with original EN file :) And I already use this translation.

I mean 🤔, diff view for the commit in pr.
pr commit diff

**Comment by RobiNN1** [comment]
This is how it looks in the original EN...

```yml
 prefix: '&e[&aCMI&e] '
  NoPermission: '&cYou don''t have permission!'
  CantHavePermission: '&cYou can''t have this permission!'
```

**Pull request closed without merging**
